<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="119095" started-at="2020-09-18T20:41:51 AEST" finished-at="2020-09-18T20:43:50 AEST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:creditorWatch.tests.TestRunner@394e1a0f]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Blog anchor text tags Validation Tests" duration-ms="119095" started-at="2020-09-18T20:41:51 AEST" finished-at="2020-09-18T20:43:50 AEST">
      <class name="creditorWatch.tests.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:creditorWatch.tests.TestRunner@394e1a0f]" name="setUpClass" is-config="true" duration-ms="207" started-at="2020-09-18T20:41:51 AEST" finished-at="2020-09-18T20:41:52 AEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:creditorWatch.tests.TestRunner@394e1a0f]" name="feature" duration-ms="118734" started-at="2020-09-18T20:41:52 AEST" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-09-18T20:43:50 AEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Validate the anchor tags text in the Blogs]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [http://www.creditsource.com.au/] but found [https://creditorwatch.com.au/blog/company-financial-statements/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [http://www.creditsource.com.au/] but found [https://creditorwatch.com.au/blog/company-financial-statements/]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [http://www.creditsource.com.au/] but found [https://creditorwatch.com.au/blog/company-financial-statements/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at creditorWatch.pageObjects.BlogPage.verifyLinks(BlogPage.java:95)
at creditorWatch.stepDefinitions.MyStepDefinitions.i_validate_all_the_anchor_tags_text_in_the_post(MyStepDefinitions.java:115)
at âœ½.Then I validate all the anchor tags text in the post Due Diligence(src/test/java/features/BlogsTest.feature:9)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:creditorWatch.tests.TestRunner@394e1a0f]" name="tearDownClass" is-config="true" duration-ms="18" started-at="2020-09-18T20:43:50 AEST" finished-at="2020-09-18T20:43:50 AEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- creditorWatch.tests.TestRunner -->
    </test> <!-- Blog anchor text tags Validation Tests -->
  </suite> <!-- Suite -->
</testng-results>
